@startuml
left to right direction
skinparam packageStyle rectangle

' Schéma de couleurs : noir sur blanc uniquement
skinparam actorBackgroundColor white
skinparam actorBorderColor black
skinparam usecaseBackgroundColor white
skinparam usecaseBorderColor black
skinparam packageBackgroundColor white
skinparam packageBorderColor black
skinparam arrowColor black

actor "Système Externe" as System

rectangle "API REST" {
  usecase "Consulter les articles" as UC_API_Articles
}

System -- UC_API_Articles

@enduml
